const movieInfo = {
  title: "some title",
  storyLine: "little bit about the movie",
  director: "123456",
  releaseDate: "07-07-2022",
  status: "private",
  type: "Movie",
  genres: ["Sci-fi", "Action"],
  tags: ["action", "movie", "hollywood"],
  cast: [{ id: "kfd2354po", roleAs: "John Doe", leadActor: true }],
  writer: ["456789sfa", "fsda589745"],
  poster: File,
  trailer: { url: "https://", public_id: "fsda589745" },
  language: "English",
};
